import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentation: [
    {
      type: 'category',
      label: 'Basics',
      collapsible: true,
      collapsed: false,
      items: ['guides/getting-started', 'guides/components-technology'],
    },
    {
      type: 'category',
      label: 'Customization',
      collapsible: true,
      collapsed: false,
      items: [
        'guides/layout-customizations-guide',
        'guides/card-form-customizations-guide',
      ],
    },
    {
      type: 'category',
      label: 'Advanced',
      collapsible: true,
      collapsed: false,
      items: [
        'guides/options-guide',
        'guides/events-guide',
        'guides/llm-guide',
      ],
    },
    {
      type: 'category',
      label: 'Frameworks',
      collapsible: true,
      collapsed: false,
      items: ['guides/react-guide', 'guides/server-side-rendering-guide'],
    },
  ],
  sdkReference: [
    {
      type: 'autogenerated',
      dirName: 'sdk-reference',
    },
  ],
};

export default sidebars;
